### ISSUE TITLE
Feature: improve adding repos in the insight page

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/insights#1508] opened 2023-08-06 18:41 UTC
### Type of feature

🍕 Feature

### Current behavior

Here is the user scenario: 
I want to add multiple repositories at the same time and search them with one keyword. 
it's not possible right now and we need to add each repo by itself, after clicking on the repo it got just added in the text field and we need to click the add repository again. 

https://github.com/open-sauced/insights/assets/18273833/0f867679-3ee7-4990-bf10-851ffd064b0d

### Suggested solution

A good example could be being able to search repos and have a search bar: 
under the search bar we would have the repositories that we need and add them, something similar to the repositories table. 

![image](https://github.com/open-sauced/insights/assets/18273833/d985cec6-d260-478c-bb7b-e82ae8368147)

another good example could be the vuetify tables: (c is the search term)

![image](https://github.com/open-sauced/insights/assets/18273833/0e60a165-1333-41e7-8f93-06fbd787b54a)

https://vuetifyjs.com/en/components/data-tables/filtering/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment] 2023-08-07 15:58
Marking as a duplicate of https://github.com/open-sauced/insights/issues/1249

**Closed by brandonroberts** 2023-08-07 15:58 UTC
Labels: 💡 feature, 👀 needs triage
