### ISSUE TITLE
Bug: Auto Summarise doesn't work sometimes, and does not exit gracefully

### ISSUE THREAD

**Issue by diivi** [open-sauced/insights#1497] opened 2023-08-06 01:06 UTC
### Describe the bug

![image](https://github.com/open-sauced/insights/assets/41837037/1486df01-77b2-4bfd-a2db-e72c40532944)
I added my PR for auto summary, but it raised some errors and the button just kept blinking. I had to reload to try again.

### Steps to reproduce

1. go to insights/feed
2. https://github.com/open-sauced/pizza-cli/pull/15 - this was the pr url
3. click on auto summarise
4. it should throw errors and get stuck in a loop (blinking)

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by diivi** [comment] 2023-08-06 01:08
This seems to be some weird authentication error, when I re login it works.

**Comment by jpmcb** [comment] 2023-08-07 18:06
This sounds like a duplicate of: https://github.com/open-sauced/insights/issues/1440 where I was also getting strange 401 with the token being null.

@diivi - do you mind reading over that issue and adding any context you can think of?

**Closed by jpmcb** 2023-08-07 18:06 UTC
Labels: 🐛 bug

**Comment by diivi** [comment] 2023-08-07 18:08
Yup, it's exactly the same thing.
