### ISSUE TITLE
Bug: Highlight filters does not work if you did not follow anyone

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/insights#1262] opened 2023-06-13 01:02 UTC
### Describe the bug

If you are a new user and open highlight, then try to check filters, the filters will require you to follow someone. 

### Steps to reproduce

1. go to beta highlights
2. click on the the filters on the right side
3. you will got a message to follow someone 

### Additional context (Is this in dev or production?)

This happened only on dev. (opening the issue to rise awearness, If i could not reproduce in the next few days, I will close it)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment] 2023-08-01 05:37
@a0m0rajab can you confirm that this is still an issue. I just checked on my second account and could not reproduce. It might of got fixed in this pr https://github.com/open-sauced/insights/pull/1426

<img width="1530" alt="Screen Shot 2023-07-31 at 10 36 20 PM" src="https://github.com/open-sauced/insights/assets/5713670/8b03e296-e206-4d1d-a7d5-311b4a405483">

**Comment by a0m0rajab** [comment] 2023-08-01 08:31
I could not replicate it right now yet the placeholder is being misleading, I think we can update it:

https://github.com/open-sauced/insights/assets/18273833/32b3b0a3-03b3-490c-9842-ef22913f2ce3

**Closed** 2023-08-07 16:18 UTC
Labels: 🐛 bug, 👀 needs triage
