### ISSUE TITLE
Feature: Add query params to the /feed endpoint

### ISSUE THREAD

**Issue by diivi** [open-sauced/insights#1175] opened 2023-05-13 07:42 UTC
### Type of feature

🍕 Feature

### Current behavior

Currently, when the OpenSauced chrome extension redirects a user to insights from their PR, nothing is pre-filled.
ref the GIF here - https://github.com/open-sauced/browser-extensions/pull/64

If the /feed endpoint accepted query params like prLink/description:

/feed?prLink=github.com/x/y/pr/55

We could fill in the PR field directly and improve UX.

### Suggested solution

Add query params support to /feed endpoint to improve third-party integrations.

This would give users another reason to use the chrome extension too! Happy to look at possible options and implement this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment] 2023-07-02 16:17
Duplicate of https://github.com/open-sauced/insights/issues/1143

**Closed by takanome-dev** 2023-07-02 16:17 UTC
Labels: duplicate, 💡 feature
