### ISSUE TITLE
Bug: AI and Machine Learning logo is not displaying in current interest

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/insights#1469] opened 2023-08-02 18:18 UTC
### Describe the bug

In the user profile the AI and Machine Learning logo is not displaying in current interest section
you can check it out here 
https://insights.opensauced.pizza/user/dev-phantom/highlights

here is a screenshot:
![Screenshot (10)](https://github.com/open-sauced/insights/assets/72051159/bbcba8f1-a789-409b-af46-1dfd8fa50262)

### Steps to reproduce

1. go to https://insights.opensauced.pizza/
2. click on the github profile picure dropdown 
3. navigate to your account profile 
4. scroll down to current interest
5. see error

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment] 2023-08-02 19:36
This is happening due to not having a logo to that category, since both of them are using a placeholder: 
https://insights.opensauced.pizza/ML/dashboard/filter/recent
https://insights.opensauced.pizza/react/dashboard/filter/recent

The src of the image is not being loaded, I think adding a default placeholder would solve the issue:  

![image](https://github.com/open-sauced/insights/assets/18273833/cc5c8c34-c0dd-496c-91be-65b8cdd2e398)

**Comment by a0m0rajab** [comment] 2023-08-02 19:43
After a quick check, I found the next; 

This is related to this code: 

https://github.com/open-sauced/insights/blob/68f66a70bef124ceecb3f2ee0952b366e208578b/components/atoms/LanguagePill/LanguagePill.tsx#L6-L7

and this line: 
https://github.com/open-sauced/insights/blob/68f66a70bef124ceecb3f2ee0952b366e208578b/components/atoms/LanguagePill/LanguagePill.tsx#L75

The issue were introduced at this PR: 
https://github.com/open-sauced/insights/pull/1010/files?diff=split&w=1

One of the things it would worth to checked is writing the topic in lowercase letters, and fixing the link issue in the ML path.

**Comment by a0m0rajab** [comment] 2023-08-02 19:44
Thank you for this issue!

**Comment by anubhav1206** [comment] 2023-08-03 05:00
Is anyone working on it?

**Comment by dev-phantom** [comment] 2023-08-03 05:13
> Is anyone working on it?

Nope

Feel free to take on this issue

**Comment by a0m0rajab** [comment] 2023-08-03 07:33
@anubhav1206 feel free to work on it. 
Removing the extra slash would solve the issue:

https://github.com/open-sauced/insights/blob/9563116227f74c44b9cc2de729f1039190db9558/components/atoms/LanguagePill/LanguagePill.tsx#L7

**Comment by anubhav1206** [comment] 2023-08-03 07:48
> @anubhav1206 feel free to work on it. Removing the extra slash would solve the issue:
> 
> https://github.com/open-sauced/insights/blob/9563116227f74c44b9cc2de729f1039190db9558/components/atoms/LanguagePill/LanguagePill.tsx#L7

sure thanks

**Comment by dev-phantom** [comment] 2023-08-11 12:50
I'm still able to reproduce this error

**Comment by dev-phantom** [comment] 2023-08-13 12:48
![Screenshot_20230813-133406](https://github.com/open-sauced/insights/assets/72051159/8f8de4ec-42b9-4330-a0ce-a281eb19fab8)
It works well on other people profile
@a0m0rajab can you reproduce this issue on your own end?

**Comment by a0m0rajab** [comment] 2023-08-13 20:28
@dev-phantom  I checked my own profile: https://deploy-preview-1474--oss-insights.netlify.app/user/a0m0rajab/highlights and it worked with me, 
![image](https://github.com/open-sauced/insights/assets/18273833/352dafff-ec70-467f-b0aa-eaf2b7744635)


I think there is another issue here that's related to backend, when I click on ML from your profile I got this link 
`https://deploy-preview-1474--oss-insights.netlify.app/ML/dashboard/filter/recent` yet when I click on the one on my profile I got this link: `https://deploy-preview-1474--oss-insights.netlify.app/ml/dashboard/filter/recent`

You can see the `ML` one of them is small letters and the other is capital letters, can you update the interests in your profile and test again?

**Comment by dev-phantom** [comment] 2023-08-13 21:02
> @dev-phantom I checked my own profile: https://deploy-preview-1474--oss-insights.netlify.app/user/a0m0rajab/highlights and it worked with me, ![image](https://user-images.githubusercontent.com/18273833/260325672-352dafff-ec70-467f-b0aa-eaf2b7744635.png)
> 
> I think there is another issue here that's related to backend, when I click on ML from your profile I got this link `https://deploy-preview-1474--oss-insights.netlify.app/ML/dashboard/filter/recent` yet when I click on the one on my profile I got this link: `https://deploy-preview-1474--oss-insights.netlify.app/ml/dashboard/filter/recent`
> 
> You can see the `ML` one of them is small letters and the other is capital letters, can you update the interests in your profile and test again?

After updating it I get this 
![Screenshot_20230813-220024](https://github.com/open-sauced/insights/assets/72051159/30103364-c07b-40d6-a959-0123600d3ee1)

Now the issue is how do I remove the previous ML and AI

**Comment by a0m0rajab** [comment] 2023-08-13 21:15
That's a good question! can you open a new issue for that? the new issue is out of scope of this issue. 
it would be great to close this and track it there.

**Closed by a0m0rajab** 2023-08-13 21:15 UTC
Labels: good first issue, 🐛 bug, released, released on @beta

**Comment by dev-phantom** [comment] 2023-08-13 21:23
> That's a good question! can you open a new issue for that? the new issue is out of scope of this issue. it would be great to close this and track it there.
> 
> Note: closing this issue since it's resolved and we got a new issue right now.

I don't think there's a need for that since I'm the only one that can reproduce this

**Comment by a0m0rajab** [comment] 2023-08-13 21:30
I think it would be nice to have it as a trigger/warning to be consistent in these things, I can have reproduce it on your account. 
![image](https://github.com/open-sauced/insights/assets/18273833/a1d43220-d900-4f82-bc30-8e4dd47f5207)

**Comment by a0m0rajab** [comment] 2023-08-13 21:31
Even if it's not solved it would be archived as in a searchable approach.

**Comment by dev-phantom** [comment] 2023-08-13 21:33
> Even if it's not solved it would be archived as in a searchable approach.

To be honest I really don't know what to put in the issue template cause that's what I've added here it will look like I'm creating a duplicate issue
