### ISSUE TITLE
Bug: Not all suggestions are being displayed on insight page

### ISSUE THREAD

**Issue by Olaleye-Blessing** [open-sauced/insights#1374] opened 2023-07-16 12:46 UTC
### Describe the bug

Just few repos are being showed when a user searches for a repo even tho the query returns many repos.

![Screenshot (782)](https://github.com/open-sauced/insights/assets/70102539/6a3c6cf2-5847-4403-a61e-463e4666c241)

### Steps to reproduce

-  Go to the page to create a new insight, [https://insights.opensauced.pizza/hub/insights/new](https://insights.opensauced.pizza/hub/insights/new)
- Open dev tools and click on the Network tab

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by aryanas159** [comment] 2023-07-17 05:15
@Olaleye-Blessing @brandonroberts 
`    if (req.ok) {
      const res = await req.json();
      const suggestions = res.items.map((item: any) => item.full_name);
      if (suggestions.length > 5) suggestions.length = 5;
      setSuggestions(suggestions);`

According to this only 5 results can be displayed, is it a bug or a feature?

**Comment by babblebey** [comment] 2023-07-17 06:37
This thus seem like it was intentional and I want to assume it was indeed made that way in the absence of a `ScrollArea` component in the `beta` design system at initial implementation.

**Here's what happen without (`if (suggestions.length > 5) suggestions.length = 5;`) limiting suggestions count to 5**

![screencast-localhost_3000-2023 07 17-07_30_36](https://github.com/open-sauced/insights/assets/25631971/5c55c8eb-772c-4658-9c93-050e15545f23)

I added a `ScrollArea` component to the design system recently #1283

Would any of you guys want to give implementing it into the `Search` component a shot?

**Comment by aryanas159** [comment] 2023-07-17 07:10
@babblebey Okay, I will try implementing it.

**Comment by babblebey** [comment] 2023-07-17 07:26
> Okay, I will try implementing it.

Great 🍕 Let us know if you need any help!

You can reference the `ScrollArea` documentation here -> [ScrollArea Story](https://design-insights.opensauced.pizza/?path=/docs/design-system-atoms-scrollarea--default)

**Comment by aryanas159** [comment] 2023-07-17 09:20
@babblebey Could you please checkout the changes I have made.

**Comment by babblebey** [comment] 2023-07-17 10:24
> Could you please checkout the changes I have made.

Great stuff @aryanas159, kindly note that your PR #1377 doesn't exactly fix this current issue. 

I have created a new issue for what your PR fixes at #1378. Take the new Issue, then edit your PR Description, relate it accordingly.

Either you or @Olaleye-Blessing can proceed to fixing this current issue with another PR.

**Comment by babblebey** [comment] 2023-07-17 12:28
Hey @aryanas159,

My apologies, I have taken notice of how separating the PRs makes them both ineffective. So let fix this!

- Commit your second change to this branch to effect the removal of line below from the `InsightPage` component
```javascript
if (suggestions.length > 5) suggestions.length = 5;
```
- Close your PR #1377 
- I will close the Issue #1378 

This way we are be able to see a working demo of the `ScrollArea` implemented with the full `suggestions` list.

**Comment by NsdHSO** [comment] 2023-07-17 12:48
@babblebey could you check this [issue](https://github.com/open-sauced/insights/issues/932) I think this is a feature, not a bug.

**Comment by NsdHSO** [comment] 2023-07-17 12:52
IMHO the page will be so huge if we drop the limitation, or we can make overflow only in the suggestions area to have scroll and see only 5 elements once,

**Comment by babblebey** [comment] 2023-07-17 13:35
> could you check this [issue](https://github.com/open-sauced/insights/issues/932) I think this is a feature, not a bug.

@NsdHSO 

True, the `TableHeader` component seen in the 'suggested solution' section of the issue #932 indeed implements the same logic in handling the `suggestions` counts as with the `InsightPage` component, that's where it must've gotten the idea from.

```javascript
if (suggestions.length > 5) suggestions.length = 5;
```

> IMHO the page will be so huge if we drop the limitation, or we can make overflow only in the suggestions area to have scroll and see only 5 elements once,

The goal is introduce all the suggestions without the limit and implement the `ScrollArea` which will surely allow us see only `5` elements at once and the rest will require a scroll _as seen below_

![screencast-localhost_3000-2023 07 17-14_01_20](https://github.com/open-sauced/insights/assets/25631971/d4bc1bbf-dce6-4138-a869-95531f69e3da)

What do you think?

**Comment by NsdHSO** [comment] 2023-07-17 13:42
I think this approach is more feasible.

**Comment by aryanas159** [comment] 2023-07-17 14:08
@babblebey I have made a different PR and closed the other two, this should fix all the issues.

**Closed** 2023-07-18 05:03 UTC
Labels: 🐛 bug, 👀 needs triage
